// SPDX-License-Identifier: GPL-3.0
pragma solidity 0.8.27;

/**
 * @dev IRequestValidator. Interface for verification of request query data.
 */
interface IRequestValidator {
    error RequestParamNameNotFound();
    error InputNameNotFound();
    /**
     * @dev ResponseField. Information about response fields from verification. Used in verify function.
     * @param name Name of the response field
     * @param value Value of the response field
     */
    struct ResponseField {
        string name;
        uint256 value;
    }

    /**
     * @dev RequestParam. Information about request param from request query data.
     * @param name Name of the request query param
     * @param value Value of the request query param
     */
    struct RequestParam {
        string name;
        uint256 value;
    }

    /**
     * @dev Get version of the contract
     */
    function version() external view returns (string memory);

    /**
     * @dev Verify the proof with the supported method informed in the request query data
     * packed as bytes and that the proof was generated by the sender.
     * @param sender Sender of the proof.
     * @param proof Proof packed as bytes to verify.
     * @param params Request query data of the credential to verify.
     * @return Array of response fields as result.
     */
    function verify(
        address sender,
        bytes calldata proof,
        bytes calldata params
    ) external returns (ResponseField[] memory);

    /**
     * @dev Get the request params of the request query data.
     * @param params Request query data of the credential to verify.
     * @return RequestParams of the request query data.
     */
    function getRequestParams(bytes calldata params) external view returns (RequestParam[] memory);

    /**
     * @dev Get the index of the request param by name
     * @param name Name of the request param
     * @return Index of the request param
     */
    function requestParamIndexOf(string memory name) external view returns (uint256);

    /**
     * @dev Get the index of the public input of the circuit by name
     * @param name Name of the public input
     * @return Index of the public input
     */
    function inputIndexOf(string memory name) external view returns (uint256);
}
