name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Get node.js
      uses: actions/setup-node@v4
      with:
        node-version: "24.17.0"
    - name: Install node_modules
      run: npm install
    - name: Test contracts
      run: npm run test
